### ISSUE TITLE
error message on game start

### ISSUE THREAD

**Issue by wh0isit** [UnRealDinnerbone/SimpleZoom#1]
**Describe the bug**
"SimpleZoom-1.14.3-2.0.0.4-universal.jar failed to load a valid ResourcePackInfo" but mod works properly.

-Minecraft Version 1.14.4
-Mod Version 1.14.3-2.0.0.4
-Minecraft Forge Version 1.14.4-28.0.18

**Additional context**
I fixed this by adding this pack.mcmeta to the jar file root.
However I have no idea of the validity of this:

> {
    "pack": {
        "description": "SimpleZoom",
        "pack_format": 4
    }
}

**Comment by UnRealDinnerbone** [comment]
There a new version out on CurseForge it should fix it
