### ISSUE TITLE
Support for 1.16.X

### ISSUE THREAD

**Issue by TheFlyron** [UnRealDinnerbone/SimpleZoom#4]
Hi there! The latest version of Minecraft this mod supports seems to be 1.15. Is there support for 1.16 in the works? Or may I contribute in some way to make this work? I'd like to use this mod in a private custom modpack.

**Comment by UnRealDinnerbone** [comment]
I kind of stop supporting this mod, there are other options out there such as WiiZoom https://www.curseforge.com/minecraft/mc-mods/wi-zoom

**Comment by TheFlyron** [comment]
That one's for Fabric though. I'm building my modpack for Forge and the options are very limited there.
