### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by ghost** [UnRealDinnerbone/SimpleZoom#5]
The game crashes on startup and displays the following error message: 
```
Simple Zoom (simplezoom) has failed to load correctly
java.lang.NoClassDefFoundError: net/minecraft/client/KeyMapping
```
Full crash report: https://pastebin.com/FT6BribU

-Minecraft Version: 1.16.5
-Mod Version: 2.4.5
-Minecraft Forge Version: 36.1.0

**Comment by UnRealDinnerbone** [comment]
this on the server?

**Comment by ghost** [comment]
I'm not sure. It crashes after the load screen but before the main menu, if that helps. I also tested it with no other mods installed, and it still crashed with the same error.

**Comment by UnRealDinnerbone** [comment]
Just pushed a new version that should hopefully fix it
