### ISSUE TITLE
Minecraft crashes with the mod on

### ISSUE THREAD

**Issue by Guest5647** [UnRealDinnerbone/SimpleZoom#6]
Here is the crash report: https://pastebin.com/TUrpe6nm
Minecraft Version: 1.16.5
Forge Version: 36.1.12
Mod Version: 2.4.5
Error Message: java.lang.noclassdeffounderror: net/minecraft/client/keymapping

**Comment by UnRealDinnerbone** [comment]
New Version On Curseforge that should fix it
